//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Candidaturas_BO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CandidaturasBOEntities : DbContext
    {
        public CandidaturasBOEntities()
            : base("name=CandidaturasBOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidato> Candidato { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Concelho> Concelho { get; set; }
        public virtual DbSet<ConhecimentoEscola> ConhecimentoEscola { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<DadosPessoais> DadosPessoais { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<DocumentoBinario> DocumentoBinario { get; set; }
        public virtual DbSet<Edicao> Edicao { get; set; }
        public virtual DbSet<EstadoCivil> EstadoCivil { get; set; }
        public virtual DbSet<Exame> Exame { get; set; }
        public virtual DbSet<Form> Form { get; set; }
        public virtual DbSet<Freguesia> Freguesia { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<Inquerito> Inquerito { get; set; }
        public virtual DbSet<Localidade> Localidade { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Posto> Posto { get; set; }
        public virtual DbSet<Ramo> Ramo { get; set; }
        public virtual DbSet<Reparticoes> Reparticoes { get; set; }
        public virtual DbSet<Situacao> Situacao { get; set; }
        public virtual DbSet<TipoDocumentoID> TipoDocumentoID { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserCurso> UserCurso { get; set; }
        public virtual DbSet<UserExame> UserExame { get; set; }
    }
}
