//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Candidaturas_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidatura()
        {
            this.Documento = new HashSet<Documento>();
            this.Historico = new HashSet<Historico>();
            this.Opcoes = new HashSet<Opcoes>();
            this.UserExame = new HashSet<UserExame>();
        }
    
        public int id { get; set; }
        public int UserId { get; set; }
        public string Edicao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
    
        public virtual Candidatura Candidatura1 { get; set; }
        public virtual Candidatura Candidatura2 { get; set; }
        public virtual Edicao Edicao1 { get; set; }
        public virtual User User { get; set; }
        public virtual Certificado Certificado { get; set; }
        public virtual DadosPessoais DadosPessoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documento> Documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historico> Historico { get; set; }
        public virtual Inquerito Inquerito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opcoes> Opcoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserExame> UserExame { get; set; }
    }
}
