//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Candidaturas_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoExame
    {
        public int CursoID { get; set; }
        public int ExameID { get; set; }
        public string Edicao { get; set; }
        public bool Obrigatorio { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Edicao Edicao1 { get; set; }
        public virtual Exame Exame { get; set; }
    }
}
