//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Candidaturas_BO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Freguesia
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        public string Nome { get; set; }

        [DisplayName("Código")]
        [Required(ErrorMessage = "Campo Obrigatório")]
        public int Codigo { get; set; }

        [DisplayName("Código Concelho")]
        [Required(ErrorMessage = "Campo Obrigatório")]
        public int CodigoConcelho { get; set; }

        [DisplayName("Código Distrito")]
        [Required(ErrorMessage = "Campo Obrigatório")]
        public int CodigoDistrito { get; set; }
    }
}
