//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Candidaturas_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico
    {
        public int id { get; set; }
        public int CandidaturaID { get; set; }
        public string mensagem { get; set; }
        public System.DateTime timestamp { get; set; }
    
        public virtual Candidatura Candidatura { get; set; }
    }
}
