//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Candidaturas_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inquerito
    {
        public int CandidaturaID { get; set; }
        public int SituacaoPai { get; set; }
        public string OutraPai { get; set; }
        public int SituacaoMae { get; set; }
        public string OutraMae { get; set; }
        public int ConhecimentoEscola { get; set; }
        public string Outro { get; set; }
        public bool CandidatarOutros { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
    
        public virtual Candidatura Candidatura { get; set; }
        public virtual ConhecimentoEscola ConhecimentoEscola1 { get; set; }
        public virtual Situacao Situacao { get; set; }
        public virtual Situacao Situacao1 { get; set; }
    }
}
