//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Candidaturas_BO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Inquerito
    {
        public int UserId { get; set; }

        [DisplayName("Situação do Pai")]
        public string SituacaoPai { get; set; }

        [DisplayName("Outra (Pai)")]
        public string OutraPai { get; set; }

        [DisplayName("Situação da Mãe")]
        public string SituacaoMae { get; set; }

        [DisplayName("Outra (Mãe)")]
        public string OutraMae { get; set; }

        [DisplayName("Como tomou conhecimento da escola?")]
        public string ConhecimentoEscola { get; set; }

        [DisplayName("Outro (Escola)")]
        public string Outro { get; set; }

        [DisplayName("Candidatou-se a outros estabelecimentos de ensino?")]
        public bool CandidatarOutros { get; set; }
        public int ID { get; set; }
    
        public virtual User User { get; set; }
    }
}
