//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Candidaturas_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Militar
    {
        public int User_ID { get; set; }
        public string Ramo { get; set; }
        public string Categoria { get; set; }
        public int Posto { get; set; }
        public string Classe { get; set; }
        public string NIM { get; set; }
    
        public virtual Categoria Categoria1 { get; set; }
        public virtual Posto Posto1 { get; set; }
        public virtual Ramo Ramo1 { get; set; }
        public virtual User User { get; set; }
    }
}
