//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Candidaturas_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reparticoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reparticoes()
        {
            this.DadosPessoais = new HashSet<DadosPessoais>();
        }
    
        public int CodigoDistrito { get; set; }
        public int CodigoConcelho { get; set; }
        public int CodigoFreguesia { get; set; }
        public int Codigo { get; set; }
        public string Nome { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DadosPessoais> DadosPessoais { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Reparticoes Reparticoes1 { get; set; }
        public virtual Reparticoes Reparticoes2 { get; set; }
    }
}
