//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Candidaturas_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExame
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public int ExameId { get; set; }
    
        public virtual Exame Exame { get; set; }
        public virtual User User { get; set; }
    }
}
