//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Candidaturas_BO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Inquerito = new HashSet<Inquerito>();
            this.UserExame = new HashSet<UserExame>();
        }
    
        public int ID { get; set; }

        [DisplayName("Nome Completo")]
        public string NomeCompleto { get; set; }
        public string Password { get; set; }
        public string NDI { get; set; }
        public bool Militar { get; set; }

        [DisplayName("Data de Nascimento")]
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public string Email { get; set; }
        public string LoginErrorMessage { get; set; }
        public string TipoDocID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inquerito> Inquerito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserExame> UserExame { get; set; }
    }
}
